### ISSUE TITLE
Don't Conflict with CLI Gem

### ISSUE THREAD

**Issue by yfeldblum** [cloudfoundry-attic/vmc#13]
If there is another gem named `cli` (such as https://rubygems.org/gems/cli), then vmc will conflict with that other gem. This is problematic.

Right now, I can

```
$ gem install vmc
$ irb
ruby > require 'cli'
 => true
ruby > VMC
 => VMC
```

This is because the file structure looks like

```
lib/
  cli/
  vmc/
  cli.rb
  vmc.rb
```

Instead, the file structure should be re-arranged to look like the standard gem structure

```
lib/
  vmc/
    cli/
    cli.rb
  vmc.rb
```

and then in order to use the cli you would do

```
  $ irb
  ruby > require 'vmc/cli'
   => true
```

**Comment by oppegard** [comment]
Please direct issues, questions, and feature requests to our Cloud Foundry community site, as that is where the majority of discussion and help occurs: http://support.cloudfoundry.com

Feel free to start a new forum thread, or open a ticket if confidential data is involved.

Thanks!

**Comment by vmware-ac-gerrit** [comment]
Dear Cloud Foundry contributor,

<p>
Thank you for your interest in Cloud Foundry. We are tracking issues in Jira at https://cloudfoundry.atlassian.net/secure/Dashboard.jspa. Please submit your issue in Jira and we will attend to it as soon as we can.
</p>


<p>
Best Regards,<br/>
Cloud Foundry Team
</p>
