### ISSUE TITLE
Remove port from suggested URL

### ISSUE THREAD

**Issue by garethr** [cloudfoundry-attic/vmc#20]
I'm accessing vcap via a non-standard port, specifically because I'm port forwarding from my local machine to a virtual machine. This works perfectly well, just use the port when calling target.

However, when creating applications via push this causes the suggested url to contain the port as well, which isn't needed and won't work for creating the app in vcap.

My branch has a fix for this at https://github.com/garethr/vmc/commit/41eda4dc1105a24d21392f992a8c131ba29d4c96

**Comment by oppegard** [comment]
Could you submit a pull request so that Cloud Foundry engineering are aware you have a code fix for this issue?

**Comment by vmware-ac-gerrit** [comment]
Dear Cloud Foundry contributor,

<p>
Thank you for your interest in Cloud Foundry. We are tracking issues in Jira at https://cloudfoundry.atlassian.net/secure/Dashboard.jspa. Please submit your issue in Jira and we will attend to it as soon as we can.
</p>


<p>
Best Regards,<br/>
Cloud Foundry Team
</p>
