### ISSUE TITLE
Service names with whitespaces or strange chars

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry-attic/vmc#26]
I can create new services with whitespace or strange chars but I'm unable to delete them. That's because vmc uses a json post for adding a new service, but an http plain post for deleting them. 

An example:

~frodenas$ vmc create-service redis "foo bar"
Creating Service: OK

~ frodenas$ vmc delete-service "foo bar"
Deleting service [foo bar]: Cannot access target (bad URI(is not URI?): http://api.cloudfoundry.com/services/foo bar)

**Comment by oppegard** [comment]
Thanks for the bug report. I've filed an issue on the internal Cloud Foundry bug tracker.

**Comment by vmware-ac-gerrit** [comment]
Dear Cloud Foundry contributor,

<p>
Thank you for your interest in Cloud Foundry. We are tracking issues in Jira at https://cloudfoundry.atlassian.net/secure/Dashboard.jspa. Please submit your issue in Jira and we will attend to it as soon as we can.
</p>


<p>
Best Regards,<br/>
Cloud Foundry Team
</p>
