### ISSUE TITLE
Dependency on rspec 1.3.2 in Rakefile should be specify.

### ISSUE THREAD

**Issue by tjyang** [cloudfoundry-attic/vmc#30]
latest rspec is 2.6.x which is incompatible with  'spec/rake/spectask' syntax.

**Comment by vmware-ac-gerrit** [comment]
Dear Cloud Foundry contributor,

<p>
Thank you for your interest in Cloud Foundry. We are tracking issues in Jira at https://cloudfoundry.atlassian.net/secure/Dashboard.jspa. Please submit your issue in Jira and we will attend to it as soon as we can.
</p>


<p>
Best Regards,<br/>
Cloud Foundry Team
</p>
