### ISSUE TITLE
Become resilient to npm packages that install symlinks in .bin

### ISSUE THREAD

**Issue by davidascher** [cloudfoundry-attic/vmc#36]
There are lots of popular nodejs modules (e.g. express, less, jade) that install symlinks in node_modules/.bin that point back to the bin subdirectory in their respective subtree.

Currently vmc update complains about them due to a failure in understanding the symlink structure:

Error: Can't deploy application containing links '/Users/davida/src/foo/node_modules/.bin/jade' that reach outside its root '/Users/davida/src/foo'

I suspect the root bug is the fact that the symlink is assessed to reach outside its root, even though it clearly isn't:

root: /Users/davida/src/foo
link: /Users/davida/src/foo/node_modules/.bin/jade

**Comment by ktyson** [comment]
Thanks. I had this same problem, trying to follow the instructions in the tutorial (link below), which being from 9 months ago, used npm bundle. The vmc I downloaded today did not have the fix yet.

http://support.cloudfoundry.com/entries/505133-deploying-a-node-js-app-with-npm-dependencies
