### ISSUE TITLE
rubyzip2 dependency is failing

### ISSUE THREAD

**Issue by trotter** [cloudfoundry-attic/vmc#37]
I can no longer `gem install vmc`, because it seems that rubyzip2, a dependency of vmc, has disappeared from the Internet. All versions have been yanked from rubygems.org and all copies on github seem to be gone. Any help on resolving this would be appreciated. Thanks.

**Comment by trotter** [comment]
It seems that postmodern (the gem maintainer) was in #rubygems yesterday asking how to remove gem forks. I've email postmodern to see if he/she can give any guidance on what should be used instead.

**Comment by derekcollison** [comment]
Seems to be here..

http://rubygems.org/gems/rubyzip2

**Comment by trotter** [comment]
Ok, so postmodern put the gem back on rubygems.org, but it's now showing a large deprecation warning saying that we should use rubyzip instead. I'll let yall decide if you want a ticket for that or not.

Guess I managed to attempt a vmc install in the short window during which rubyzip2 was nowhere to be found. I'm closing the issue now, as I don't think anyone else will hit this particular problem.
