### ISSUE TITLE
new vmc manifests feature should support --runtime

### ISSUE THREAD

**Issue by pbm** [cloudfoundry-attic/vmc#44]
For ruby apps, it would be nice to capture the --runtime ruby18 vs --runtime ruby19 setting in the manifest.yml file

**Comment by pbm** [comment]
And, as long as I'm asking for feature enhancements, it might be nice if "vmc logs" and "vmc crashlogs" would pull the appname out of ./manifest.yml

**Comment by vmware-ac-gerrit** [comment]
Dear Cloud Foundry contributor,

<p>
Thank you for your interest in Cloud Foundry. We are tracking issues in Jira at https://cloudfoundry.atlassian.net/secure/Dashboard.jspa. Please submit your issue in Jira and we will attend to it as soon as we can.
</p>


<p>
Best Regards,<br/>
Cloud Foundry Team
</p>
