### ISSUE TITLE
add .vmcignore file for vmc push (and document current filters)

### ISSUE THREAD

**Issue by pbm** [cloudfoundry-attic/vmc#47]
It seems that when you do a "vmc push", not all files will get pushed up to cloudfoundry (they are note found when I do "vmc files myapp app").  Currently, it looks like .git, .svn, *~, #foo log/development.log are filtered.  But some files that you might want to prevent being uploaded do get uploaded (e.g., I tried log/development.log-orig, which got uploaded).

I think there should be a mechanism for the developer to specify a set of files to ignore during upload, and there should be some clear documentation as to which files are already filtered.  I should be able to prevent entire directories "log", allow a directory, but not contents "log/*_/_" and filetypes *.sqlite3.

**Comment by leto** [comment]
+1

**Comment by wallyqs** [comment]
+1, this feature would be nice to have. In my opinion, the way that files are being ignored right now might not be very intuitive for some. For example, currently `.htaccess` files at root are being ignored after a vmc push.
https://github.com/cloudfoundry/vcap/pull/165

**Comment by schinen** [comment]
+1

**Comment by schinen** [comment]
I inquired about this feature on support forum.
http://support.cloudfoundry.com/entries/21098173-about-vmcignore-file-for-vmc-content-filtering-feature

The reply from cloud foundry team is folloing.

> I reviewed this with engineering, and it is active and in the works. :-)

**Comment by njh** [comment]
+1 yes please!

**Comment by vmware-ac-gerrit** [comment]
Dear Cloud Foundry contributor,

<p>
Thank you for your interest in Cloud Foundry. We are tracking issues in Jira at https://cloudfoundry.atlassian.net/secure/Dashboard.jspa. Please submit your issue in Jira and we will attend to it as soon as we can.
</p>


<p>
Best Regards,<br/>
Cloud Foundry Team
</p>

**Comment by cf-frontend** [comment]
This has been done for a while; accidental reopen?
