### ISSUE TITLE
"unknown file type META-INF/maven/" when trying to upload war file

### ISSUE THREAD

**Issue by sirmyron** [cloudfoundry-attic/vmc#48]
E:\deploy-war>vmc push test-app
Would you like to deploy from the current directory? [Yn]:
Pushing application 'test-app'...
Creating Application: OK
Uploading Application:
unknown file type META-INF/maven/
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.6.1/lib/zip/zip_entry.rb:209:in `extract'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/zip_util.rb:46:in`block in unpack'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.6.1/lib/zip/zip_entry_set.rb:31:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.6.1/lib/zip/zip_entry_set.rb:31:in`each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.6.1/lib/zip/zip_central_directory.rb:113:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.6.1/lib/zip/zip_file.rb:117:in`block in foreach'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.6.1/lib/zip/zip_file.rb:86:in `open'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.6.1/lib/zip/zip_file.rb:116:in`foreach'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/zip_util.rb:42:in `unpack'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/commands/apps.rb:416:in`block in upload_app_bits'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/commands/apps.rb:413:in `chdir'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/commands/apps.rb:413:in`upload_app_bits'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/commands/apps.rb:1015:in `do_push'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/commands/apps.rb:302:in`block in push'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/manifest_helper.rb:28:in `block in each_app'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/manifest_helper.rb:23:in`each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/manifest_helper.rb:23:in `each_app'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/commands/apps.rb:300:in`push'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/runner.rb:454:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/lib/cli/runner.rb:14:in`run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/vmc-0.3.16.beta.3/bin/vmc:5:in `<top (required)>'
C:/Ruby193/bin/vmc:19:in`load'
C:/Ruby193/bin/vmc:19:in `<main>'

**Comment by leto** [comment]
Since this is an error you got when trying to send something to cloudfoundry.com, reporting this on http://support.cloudfoundry.com is what you want.

**Comment by eeichinger** [comment]
that is a too quick closing this issue - I get exactly the same result deploying to microcloudfoundry. In contrast to the reporter above I deploy from a ubuntu server x64 machine and using both, ruby 1.9.2-p290 and ruby 1.9.3-p0. 
Interestingly exactly the same confguration on windows works for me.

**Comment by eeichinger** [comment]
here's my result

ubuntu@ubuntu:~/tmp/deploy$ vmc update myapp --path .
Uploading Application:
unknown file type META-INF/maven/
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/rubyzip-0.9.6.1/lib/zip/zip_entry.rb:209:in `extract'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/vmc-0.3.16.beta.3/lib/cli/zip_util.rb:46:in`block in unpack'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/rubyzip-0.9.6.1/lib/zip/zip_entry_set.rb:31:in `each'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/rubyzip-0.9.6.1/lib/zip/zip_entry_set.rb:31:in`each'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/rubyzip-0.9.6.1/lib/zip/zip_central_directory.rb:113:in `each'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/rubyzip-0.9.6.1/lib/zip/zip_file.rb:117:in`block in foreach'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/rubyzip-0.9.6.1/lib/zip/zip_file.rb:86:in `open'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/rubyzip-0.9.6.1/lib/zip/zip_file.rb:116:in`foreach'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/vmc-0.3.16.beta.3/lib/cli/zip_util.rb:42:in `unpack'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/vmc-0.3.16.beta.3/lib/cli/commands/apps.rb:416:in`block in upload_app_bits'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/vmc-0.3.16.beta.3/lib/cli/commands/apps.rb:413:in `chdir'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/vmc-0.3.16.beta.3/lib/cli/commands/apps.rb:413:in`upload_app_bits'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/vmc-0.3.16.beta.3/lib/cli/commands/apps.rb:274:in `update'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/vmc-0.3.16.beta.3/lib/cli/runner.rb:454:in`run'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/vmc-0.3.16.beta.3/lib/cli/runner.rb:14:in `run'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/gems/vmc-0.3.16.beta.3/bin/vmc:5:in`<top (required)>'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/bin/vmc:19:in `load'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p0/bin/vmc:19:in`<main>'

also tried with ruby 1.9.2-p290

**Comment by dsyer** [comment]
We saw this with all the windows users at QCon London.  We found a workaround which also worked for all of them, which is to open up the war file and delete the META-INF/maven directory.  It looks like maybe a native zip library issue?

**Comment by eeichinger** [comment]
I see the same problem on some of our ubuntus. Below are the gems on ubuntu 10.04 where I am fighting this problem right now. I just did a gem update to get the latest versions and reverted addressable from 2.2.7 to 2.2.6:

addressable (2.2.6)
bundler (1.1.2, 1.0.22)
interact (0.4.1, 0.4)
json_pure (1.6.5)
mime-types (1.18, 1.17.2)
rake (0.9.2.2, 0.9.2)
rest-client (1.6.7)
rubyzip (0.9.6.1)
terminal-table (1.4.5, 1.4.4)
uuidtools (2.1.2)
vmc (0.3.16.beta.5, 0.3.16.beta.3)

**Comment by eeichinger** [comment]
in my case I could fix the pb on ubuntu by editing zip_entry.rb in rubyzip-0.9.6.1: on line 361 comment out the entire "when FSTYPE_UNIX" branch
it seems rubyzip doesn't recognize the ftype correctly on unix

**Comment by vmware-ac-gerrit** [comment]
Dear Cloud Foundry contributor,

<p>
Thank you for your interest in Cloud Foundry. We are tracking issues in Jira at https://cloudfoundry.atlassian.net/secure/Dashboard.jspa. Please submit your issue in Jira and we will attend to it as soon as we can.
</p>


<p>
Best Regards,<br/>
Cloud Foundry Team
</p>
