### ISSUE TITLE
vmc targets returning an error when no auth token are defined

### ISSUE THREAD

**Issue by gbataille** [cloudfoundry-attic/vmc#52]
undefined method 'empty?' for nil:NilClass
/home/greg/cloudfoundry/.deployments/devbox/deploy/rubies/ruby-1.9.2-p180/lib/ruby/gems/1.9.1/gems/vmc-0.3.15/lib/cli/commands/misc.rb:16:in `'targets'

tracked it to _vmc-0.3.15/lib/cli/config.rb_

```
def all_tokens
token_file = File.expand_path(TOKEN_FILE)
return nil unless File.exists? token_file
contents = lock_and_read(token_file).strip
JSON.parse(contents)
end
alias :targets :all_tokens
```

Should either not return nil or vmc misc.rb targets method should handle it (certainly the latter).

Might try to propose a fix tomorrow

**Comment by vmware-ac-gerrit** [comment]
Dear Cloud Foundry contributor,

<p>
Thank you for your interest in Cloud Foundry. We are tracking issues in Jira at https://cloudfoundry.atlassian.net/secure/Dashboard.jspa. Please submit your issue in Jira and we will attend to it as soon as we can.
</p>


<p>
Best Regards,<br/>
Cloud Foundry Team
</p>
