### ISSUE TITLE
vmc register doesn't work if the cloud_controller doesn't use UAA

### ISSUE THREAD

**Issue by andreacampi** [cloudfoundry-attic/vmc#59]
With vmc 0.5.0.beta.12:

```
[andrea@ac hello]$ vmc register user@example.com
Password> ****

Confirm Password> ****
NoMethodError: undefined method `request_uri' for #<URI::Generic:0x007fb0c38b9540 URL:/password/score>
For more information, see ~/.vmc/crash
```

```
[andrea@ac hello]$ cat ~/.vmc/crash
Time of crash:
  2013-02-16 21:21:08 +0100

NoMethodError: undefined method `request_uri' for #<URI::Generic:0x007fb0c38b9540 URL:/password/score>

cf-uaa-lib-1.3.7/lib/uaa/http.rb:145:in `net_http_request'
cf-uaa-lib-1.3.7/lib/uaa/http.rb:129:in `request'
cf-uaa-lib-1.3.7/lib/uaa/misc.rb:100:in `password_strength'
cfoundry-0.5.0/lib/cfoundry/uaaclient.rb:46:in `block in password_score'
cfoundry-0.5.0/lib/cfoundry/uaaclient.rb:89:in `wrap_uaa_errors'
cfoundry-0.5.0/lib/cfoundry/uaaclient.rb:45:in `password_score'
vmc-0.5.0.beta.12/lib/vmc/cli/user/base.rb:22:in `validate_password_strength!'
vmc-0.5.0.beta.12/lib/vmc/cli/user/base.rb:14:in `validate_password!'
vmc-0.5.0.beta.12/lib/vmc/cli/user/register.rb:17:in `register'
mothership-0.5.0/lib/mothership/base.rb:66:in `run'
mothership-0.5.0/lib/mothership/command.rb:72:in `block in invoke'
mothership-0.5.0/lib/mothership/command.rb:86:in `instance_exec'
mothership-0.5.0/lib/mothership/command.rb:86:in `invoke'
mothership-0.5.0/lib/mothership/base.rb:55:in `execute'
vmc-0.5.0.beta.12/lib/vmc/cli.rb:105:in `execute'
mothership-0.5.0/lib/mothership.rb:45:in `start'
vmc-0.5.0.beta.12/bin/vmc:11:in `<top (required)>'
ruby-1.9.3-p286@chef/bin/vmc:19:in `load'
ruby-1.9.3-p286@chef/bin/vmc:19:in `<main>'
ruby-1.9.3-p286@chef/bin/ruby_noexec_wrapper:14:in `eval'
ruby-1.9.3-p286@chef/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by dsyer** [comment]
As far as I know that is by design.  The cloud controller only ever worked without the UAA in a transitional period.  The new v2 cloud controller stores no identity data at all (sensibly by design), so it's not really an option in the future to have no UAA on the server.  Therefore it doesn't make sense to support it on the client.

I do know that some work was being done recently to make vmc work for account management (as well as authentication) using only the UAA (if you have an admin login to start with).  Probably we should watch out for that rather than focus on legacy features.

**Comment by andreacampi** [comment]
FWIW the v1 cloud controller still works just fine without the UAA.
If the v2 cloud controller doesn't support that configuration then yeah, you're probably right, it's not worth spending too much time.

It's just that well, vmc 0.4.x supported it so it's kind of a shame.
Oh well, I will document that cloudfoundry-vagrant can't work with vmc 0.5.x.

**Comment by vito** [comment]
This is definitely a regression; cfoundry supports both authentication methods, but it looks like vmc assumes UAA. It's not too hard to support both, so this issue is worth fixing.

**Comment by cf-frontend** [comment]
Try with rc2.
- Alex & Dennis & Ian & Sheel

**Comment by andreacampi** [comment]
Looks good, thanks!
