### ISSUE TITLE
unable to bind serivce to app due to VMC error

### ISSUE THREAD

**Issue by cnZach** [cloudfoundry-attic/vmc#61]
For VMC 0.4.7,

Time of crash:
  2013-02-27 16:17:34 +0800

NoMethodError: undefined method `service_by_name' for #CFoundry::V1::Client:0x00000001f92508

vmc-0.4.7/lib/vmc/cli.rb:406:in `block in by_name'
mothership-0.3.5/lib/mothership/inputs.rb:150:in`instance_exec'
mothership-0.3.5/lib/mothership/inputs.rb:150:in `convert_given'
mothership-0.3.5/lib/mothership/inputs.rb:113:in`get'
mothership-0.3.5/lib/mothership/inputs.rb:69:in `[]'
vmc-0.4.7/lib/vmc/cli/service/bind.rb:15:in`bind_service'
mothership-0.3.5/lib/mothership/base.rb:61:in `run'
mothership-0.3.5/lib/mothership/command.rb:68:in`block in invoke'
mothership-0.3.5/lib/mothership/command.rb:82:in `instance_exec'
mothership-0.3.5/lib/mothership/command.rb:82:in`invoke'
mothership-0.3.5/lib/mothership/base.rb:50:in `execute'
vmc-0.4.7/lib/vmc/cli.rb:106:in`execute'
mothership-0.3.5/lib/mothership.rb:45:in `start'
vmc-0.4.7/bin/vmc:11:in`<top (required)>'
/opt/cf/.deployments/devbox/deploy/rubies/ruby-1.9.2-p180/bin/vmc:23:in `load'
/opt/cf/.deployments/devbox/deploy/rubies/ruby-1.9.2-p180/bin/vmc:23:in`<main>'

original CF-216

**Comment by andypiper** [comment]
Have you tried with vmc 0.5.x? 'gem install vmc --pre'

**Comment by cnZach** [comment]
vmc 0.5.0 rc1 works fine.  Thanks Andypiper!
