### ISSUE TITLE
Broken set-env when value contains = signal

### ISSUE THREAD

**Issue by mergulhao** [cloudfoundry-attic/vmc#69]
If I do: 

$ vmc set-env my-app BLA="-Dfile.encoding=UTF-8"

What I get is:

$ vmc env my-app
Using manifest file manifest.yml

Getting env for my-app... OK

BLA: -Dfile.encoding

**Comment by dmrschmidt** [comment]
Can you try `$ vmc set-env my-app BLA "-Dfile.encoding=UTF-8"` so just get rid of the first equal sign?

That should do the trick.
