### ISSUE TITLE
Use supported framework detection rules from vcap

### ISSUE THREAD

**Issue by blowmage** [cloudfoundry-attic/vmc#7]
vmc should query the target API for the supported frameworks and the associated detection rules. The rules for detecting a local application's framework should not be hardcoded in the gem.

**Comment by derekcollison** [comment]
We have this in the works, and frameworks and runtimes are pulled from the target cloud today. The detection code is also downloaded from the target cloud, but you are correct we currently still use the static detection code.

vmc info -t

**Comment by blowmage** [comment]
Its a week later and I still don't see how this issue is resolved. The issue was closed so I'm assuming you don't want a pull request. Is that the case? Do you have unpublished code where this is working?

**Comment by derekcollison** [comment]
We are working on utilizing the dynamic code detection that is sent from the CloudController. We do not have an ETA as of yet to deploy the code.
