### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by semmypurewal** [cloudfoundry-attic/vmc#70]
According to the README, VMC is "Deprecated." To me, that means it should no longer be used.

On the other hand, the cf client does not correctly target api.cloudfoundry.com: The error is

`V1 targets are no longer supported.`

According to a response I received on Twitter, VMC is still the correct client to use for connecting to api.cloudfoundry.com:

https://twitter.com/cloudfoundry/status/322041328101888001

Also, according to this recently closed issue on the cf project, VMC is still the correct client to use when targeting api.cloudfoundry.com:

https://github.com/cloudfoundry/cf/issues/1

I wonder if it might be helpful to make this clearer in the documentation and in the README file. Perhaps "Deprecated" is not the best choice of words at this time.

**Comment by mreider** [comment]
I am going to update the README and the docs.

**Comment by andypiper** [comment]
Thanks @mreider ('twas I that issued the tweet) - definitely need to be able to guide users to the correct tool so thanks for the feedback @semmypurewal
