### ISSUE TITLE
Poor diagnostics when vmc is used against v2 CF instance

### ISSUE THREAD

**Issue by glyn** [cloudfoundry-attic/vmc#73]
I recently targeted a v2 deployment in order to debug a v2 bug but was unaware that "vmc" has been superseded by "cf" (at least that's what a colleague told me). I got an obscure crash during vmc push rather than a helpful diagnostic much earlier. Ideally I would like a message like "use the cf gem" but I would settle for an error code that could quickly be traced to the need to use the cf gem.

If thousands of vmc users are going to migrate to use v2, this will be a common complaint and waste of people's time.

**Comment by dmrschmidt** [comment]
Sounds like a good idea. We've put a story for this in our backlog. Thanks

**Comment by glyn** [comment]
Thanks. Please could you provide a link to the story as I'd like to follow it.

**Comment by dmrschmidt** [comment]
The Tracker we use internally is unfortunately not publicly accessible for the time being. The url to the story however would be https://www.pivotaltracker.com/story/show/46236885. I can't tell right now if you may have read permissions.

**Comment by glyn** [comment]
Thanks Dennis. I hope to get access before much longer.

**Comment by andypiper** [comment]
@glyn I think @mreider or @jambay should be able to provide you with Tracker access, drop them a line.
