### ISSUE TITLE
Rubygems.org 500 Error

### ISSUE THREAD

**Issue by markgirling** [cloudfoundry-attic/vmc#74]
Hello

We are having an issue in some of our ruby projects where the VMC gem exists in the project's gem dependencies. Bundle install fails with an "Internal Server Error" message. I believe this is because bundler is trying to access this endpoint: https://api.rubygems.org/api/v1/dependencies?gems=vmc

The endpoint returns a 500 error for the vmc gem, but for other gems the endpoint serves the gem's dependencies file like normal.

Mark

**Comment by flavorjones** [comment]
Hi @markgirling, thanks for reporting this. I'm not sure yet what we can do from our end as a gem publisher, but I'm trying to figure something out.

Have you reported this to rubygems.org at all?

**Comment by flavorjones** [comment]
Ah, looks like it's been reported: https://github.com/rubygems/rubygems/issues/1439

**Comment by flavorjones** [comment]
Rubygems.org fixed this issue server-side. Closing.
