### ISSUE TITLE
Restler call causes 502

### ISSUE THREAD

**Issue by amaltson** [cloudfoundry-attic/vmc#8]
I tried to deploy a simple node demo I've been working on [here](http://osswatch.cloudfoundry.com/). It uses restler to communicate with a REST API (the github API in this case). When I push this app to cloudfoundry, it doesn't work and gets a 502. The logs don't say anything.

When I removed the restler call and just return a string, it works fine. Does cloud foundry restrict internet calls out?

**Comment by derekcollison** [comment]
You need to utilize the http_proxy that is currently in Cloud Foundry. I posted a response and a code snippet here..
http://support.cloudfoundry.com/entries/20042191-is-it-possible-to-make-external-http-requests

**Comment by amaltson** [comment]
Works perfectly, thanks.
