### ISSUE TITLE
Help doesn't detail how to choose a runtime

### ISSUE THREAD

**Issue by bfad** [cloudfoundry-attic/vmc#9]
I needed to choose the ruby19 runtime, but couldn't find anything in the help on how to create new applications or modify current applications to use that runtime instead of the ruby18.

**Comment by derekcollison** [comment]
Currently you can't modify an existing application to use a different runtime. We are working to make it easier to understand how to select different options. For now, you can try the following.

vmc help
vmc help options
vmc help <command>

We will continue to try to make these better. Thanks.
